apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-rest-api
  template:
    metadata:
      labels:
        app: node-rest-api
    spec:
      containers:
        - name: node-rest-api
          image: jeiyashivani/my-gitops-app:20251022131157
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
