apiVersion: v1
kind: Service
metadata:
  name: node-api-service
spec:
  selector:
    app: node-rest-api
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 5000 
  type: NodePort      

