name: CI/CD GitOps Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: vars
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=${TIMESTAMP}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-gitops-app:${{ env.IMAGE_TAG }} ./node-app

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-gitops-app:${{ env.IMAGE_TAG }}

      - name: Update deployment.yaml
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/my-gitops-app:${{ env.IMAGE_TAG }}|g" Deployment.yaml

      - name: Commit deployment update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Deployment.yaml
          git commit -m "Update deployment image to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
          git push origin main

